// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"your-damain.com/swagger/looker-api-golang/models"
)

// NewCreateDashboardElementParams creates a new CreateDashboardElementParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDashboardElementParams() *CreateDashboardElementParams {
	return &CreateDashboardElementParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDashboardElementParamsWithTimeout creates a new CreateDashboardElementParams object
// with the ability to set a timeout on a request.
func NewCreateDashboardElementParamsWithTimeout(timeout time.Duration) *CreateDashboardElementParams {
	return &CreateDashboardElementParams{
		timeout: timeout,
	}
}

// NewCreateDashboardElementParamsWithContext creates a new CreateDashboardElementParams object
// with the ability to set a context for a request.
func NewCreateDashboardElementParamsWithContext(ctx context.Context) *CreateDashboardElementParams {
	return &CreateDashboardElementParams{
		Context: ctx,
	}
}

// NewCreateDashboardElementParamsWithHTTPClient creates a new CreateDashboardElementParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDashboardElementParamsWithHTTPClient(client *http.Client) *CreateDashboardElementParams {
	return &CreateDashboardElementParams{
		HTTPClient: client,
	}
}

/* CreateDashboardElementParams contains all the parameters to send to the API endpoint
   for the create dashboard element operation.

   Typically these are written to a http.Request.
*/
type CreateDashboardElementParams struct {

	/* Body.

	   DashboardElement
	*/
	Body *models.DashboardElement

	/* Fields.

	   Requested fields.
	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create dashboard element params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDashboardElementParams) WithDefaults() *CreateDashboardElementParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create dashboard element params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDashboardElementParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create dashboard element params
func (o *CreateDashboardElementParams) WithTimeout(timeout time.Duration) *CreateDashboardElementParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create dashboard element params
func (o *CreateDashboardElementParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create dashboard element params
func (o *CreateDashboardElementParams) WithContext(ctx context.Context) *CreateDashboardElementParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create dashboard element params
func (o *CreateDashboardElementParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create dashboard element params
func (o *CreateDashboardElementParams) WithHTTPClient(client *http.Client) *CreateDashboardElementParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create dashboard element params
func (o *CreateDashboardElementParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create dashboard element params
func (o *CreateDashboardElementParams) WithBody(body *models.DashboardElement) *CreateDashboardElementParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create dashboard element params
func (o *CreateDashboardElementParams) SetBody(body *models.DashboardElement) {
	o.Body = body
}

// WithFields adds the fields to the create dashboard element params
func (o *CreateDashboardElementParams) WithFields(fields *string) *CreateDashboardElementParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the create dashboard element params
func (o *CreateDashboardElementParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDashboardElementParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
