// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/billtrust/looker-go-sdk/models"
)

// DashboardLayoutDashboardLayoutComponentsReader is a Reader for the DashboardLayoutDashboardLayoutComponents structure.
type DashboardLayoutDashboardLayoutComponentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DashboardLayoutDashboardLayoutComponentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDashboardLayoutDashboardLayoutComponentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDashboardLayoutDashboardLayoutComponentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDashboardLayoutDashboardLayoutComponentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDashboardLayoutDashboardLayoutComponentsOK creates a DashboardLayoutDashboardLayoutComponentsOK with default headers values
func NewDashboardLayoutDashboardLayoutComponentsOK() *DashboardLayoutDashboardLayoutComponentsOK {
	return &DashboardLayoutDashboardLayoutComponentsOK{}
}

/* DashboardLayoutDashboardLayoutComponentsOK describes a response with status code 200, with default header values.

DashboardLayoutComponent
*/
type DashboardLayoutDashboardLayoutComponentsOK struct {
	Payload []*models.DashboardLayoutComponent
}

func (o *DashboardLayoutDashboardLayoutComponentsOK) Error() string {
	return fmt.Sprintf("[GET /dashboard_layouts/{dashboard_layout_id}/dashboard_layout_components][%d] dashboardLayoutDashboardLayoutComponentsOK  %+v", 200, o.Payload)
}
func (o *DashboardLayoutDashboardLayoutComponentsOK) GetPayload() []*models.DashboardLayoutComponent {
	return o.Payload
}

func (o *DashboardLayoutDashboardLayoutComponentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardLayoutDashboardLayoutComponentsBadRequest creates a DashboardLayoutDashboardLayoutComponentsBadRequest with default headers values
func NewDashboardLayoutDashboardLayoutComponentsBadRequest() *DashboardLayoutDashboardLayoutComponentsBadRequest {
	return &DashboardLayoutDashboardLayoutComponentsBadRequest{}
}

/* DashboardLayoutDashboardLayoutComponentsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DashboardLayoutDashboardLayoutComponentsBadRequest struct {
	Payload *models.Error
}

func (o *DashboardLayoutDashboardLayoutComponentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /dashboard_layouts/{dashboard_layout_id}/dashboard_layout_components][%d] dashboardLayoutDashboardLayoutComponentsBadRequest  %+v", 400, o.Payload)
}
func (o *DashboardLayoutDashboardLayoutComponentsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DashboardLayoutDashboardLayoutComponentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDashboardLayoutDashboardLayoutComponentsNotFound creates a DashboardLayoutDashboardLayoutComponentsNotFound with default headers values
func NewDashboardLayoutDashboardLayoutComponentsNotFound() *DashboardLayoutDashboardLayoutComponentsNotFound {
	return &DashboardLayoutDashboardLayoutComponentsNotFound{}
}

/* DashboardLayoutDashboardLayoutComponentsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DashboardLayoutDashboardLayoutComponentsNotFound struct {
	Payload *models.Error
}

func (o *DashboardLayoutDashboardLayoutComponentsNotFound) Error() string {
	return fmt.Sprintf("[GET /dashboard_layouts/{dashboard_layout_id}/dashboard_layout_components][%d] dashboardLayoutDashboardLayoutComponentsNotFound  %+v", 404, o.Payload)
}
func (o *DashboardLayoutDashboardLayoutComponentsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DashboardLayoutDashboardLayoutComponentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
