// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDashboardParams creates a new DashboardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDashboardParams() *DashboardParams {
	return &DashboardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDashboardParamsWithTimeout creates a new DashboardParams object
// with the ability to set a timeout on a request.
func NewDashboardParamsWithTimeout(timeout time.Duration) *DashboardParams {
	return &DashboardParams{
		timeout: timeout,
	}
}

// NewDashboardParamsWithContext creates a new DashboardParams object
// with the ability to set a context for a request.
func NewDashboardParamsWithContext(ctx context.Context) *DashboardParams {
	return &DashboardParams{
		Context: ctx,
	}
}

// NewDashboardParamsWithHTTPClient creates a new DashboardParams object
// with the ability to set a custom HTTPClient for a request.
func NewDashboardParamsWithHTTPClient(client *http.Client) *DashboardParams {
	return &DashboardParams{
		HTTPClient: client,
	}
}

/* DashboardParams contains all the parameters to send to the API endpoint
   for the dashboard operation.

   Typically these are written to a http.Request.
*/
type DashboardParams struct {

	/* DashboardID.

	   Id of dashboard
	*/
	DashboardID string

	/* Fields.

	   Requested fields.
	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dashboard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DashboardParams) WithDefaults() *DashboardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dashboard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DashboardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dashboard params
func (o *DashboardParams) WithTimeout(timeout time.Duration) *DashboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dashboard params
func (o *DashboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dashboard params
func (o *DashboardParams) WithContext(ctx context.Context) *DashboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dashboard params
func (o *DashboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dashboard params
func (o *DashboardParams) WithHTTPClient(client *http.Client) *DashboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dashboard params
func (o *DashboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDashboardID adds the dashboardID to the dashboard params
func (o *DashboardParams) WithDashboardID(dashboardID string) *DashboardParams {
	o.SetDashboardID(dashboardID)
	return o
}

// SetDashboardID adds the dashboardId to the dashboard params
func (o *DashboardParams) SetDashboardID(dashboardID string) {
	o.DashboardID = dashboardID
}

// WithFields adds the fields to the dashboard params
func (o *DashboardParams) WithFields(fields *string) *DashboardParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the dashboard params
func (o *DashboardParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *DashboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dashboard_id
	if err := r.SetPathParam("dashboard_id", o.DashboardID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
