// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/billtrust/looker-go-sdk/models"
)

// UpdateDashboardFilterReader is a Reader for the UpdateDashboardFilter structure.
type UpdateDashboardFilterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDashboardFilterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDashboardFilterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateDashboardFilterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateDashboardFilterNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateDashboardFilterUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateDashboardFilterTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDashboardFilterOK creates a UpdateDashboardFilterOK with default headers values
func NewUpdateDashboardFilterOK() *UpdateDashboardFilterOK {
	return &UpdateDashboardFilterOK{}
}

/* UpdateDashboardFilterOK describes a response with status code 200, with default header values.

Dashboard Filter
*/
type UpdateDashboardFilterOK struct {
	Payload *models.DashboardFilter
}

func (o *UpdateDashboardFilterOK) Error() string {
	return fmt.Sprintf("[PATCH /dashboard_filters/{dashboard_filter_id}][%d] updateDashboardFilterOK  %+v", 200, o.Payload)
}
func (o *UpdateDashboardFilterOK) GetPayload() *models.DashboardFilter {
	return o.Payload
}

func (o *UpdateDashboardFilterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DashboardFilter)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardFilterBadRequest creates a UpdateDashboardFilterBadRequest with default headers values
func NewUpdateDashboardFilterBadRequest() *UpdateDashboardFilterBadRequest {
	return &UpdateDashboardFilterBadRequest{}
}

/* UpdateDashboardFilterBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateDashboardFilterBadRequest struct {
	Payload *models.Error
}

func (o *UpdateDashboardFilterBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /dashboard_filters/{dashboard_filter_id}][%d] updateDashboardFilterBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateDashboardFilterBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateDashboardFilterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardFilterNotFound creates a UpdateDashboardFilterNotFound with default headers values
func NewUpdateDashboardFilterNotFound() *UpdateDashboardFilterNotFound {
	return &UpdateDashboardFilterNotFound{}
}

/* UpdateDashboardFilterNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateDashboardFilterNotFound struct {
	Payload *models.Error
}

func (o *UpdateDashboardFilterNotFound) Error() string {
	return fmt.Sprintf("[PATCH /dashboard_filters/{dashboard_filter_id}][%d] updateDashboardFilterNotFound  %+v", 404, o.Payload)
}
func (o *UpdateDashboardFilterNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateDashboardFilterNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardFilterUnprocessableEntity creates a UpdateDashboardFilterUnprocessableEntity with default headers values
func NewUpdateDashboardFilterUnprocessableEntity() *UpdateDashboardFilterUnprocessableEntity {
	return &UpdateDashboardFilterUnprocessableEntity{}
}

/* UpdateDashboardFilterUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type UpdateDashboardFilterUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateDashboardFilterUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PATCH /dashboard_filters/{dashboard_filter_id}][%d] updateDashboardFilterUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *UpdateDashboardFilterUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateDashboardFilterUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDashboardFilterTooManyRequests creates a UpdateDashboardFilterTooManyRequests with default headers values
func NewUpdateDashboardFilterTooManyRequests() *UpdateDashboardFilterTooManyRequests {
	return &UpdateDashboardFilterTooManyRequests{}
}

/* UpdateDashboardFilterTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type UpdateDashboardFilterTooManyRequests struct {
	Payload *models.Error
}

func (o *UpdateDashboardFilterTooManyRequests) Error() string {
	return fmt.Sprintf("[PATCH /dashboard_filters/{dashboard_filter_id}][%d] updateDashboardFilterTooManyRequests  %+v", 429, o.Payload)
}
func (o *UpdateDashboardFilterTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateDashboardFilterTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
