// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/billtrust/looker-go-sdk/models"
)

// NewUpdateDashboardLayoutComponentParams creates a new UpdateDashboardLayoutComponentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDashboardLayoutComponentParams() *UpdateDashboardLayoutComponentParams {
	return &UpdateDashboardLayoutComponentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDashboardLayoutComponentParamsWithTimeout creates a new UpdateDashboardLayoutComponentParams object
// with the ability to set a timeout on a request.
func NewUpdateDashboardLayoutComponentParamsWithTimeout(timeout time.Duration) *UpdateDashboardLayoutComponentParams {
	return &UpdateDashboardLayoutComponentParams{
		timeout: timeout,
	}
}

// NewUpdateDashboardLayoutComponentParamsWithContext creates a new UpdateDashboardLayoutComponentParams object
// with the ability to set a context for a request.
func NewUpdateDashboardLayoutComponentParamsWithContext(ctx context.Context) *UpdateDashboardLayoutComponentParams {
	return &UpdateDashboardLayoutComponentParams{
		Context: ctx,
	}
}

// NewUpdateDashboardLayoutComponentParamsWithHTTPClient creates a new UpdateDashboardLayoutComponentParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDashboardLayoutComponentParamsWithHTTPClient(client *http.Client) *UpdateDashboardLayoutComponentParams {
	return &UpdateDashboardLayoutComponentParams{
		HTTPClient: client,
	}
}

/* UpdateDashboardLayoutComponentParams contains all the parameters to send to the API endpoint
   for the update dashboard layout component operation.

   Typically these are written to a http.Request.
*/
type UpdateDashboardLayoutComponentParams struct {

	/* Body.

	   DashboardLayoutComponent
	*/
	Body *models.DashboardLayoutComponent

	/* DashboardLayoutComponentID.

	   Id of dashboard layout component
	*/
	DashboardLayoutComponentID string

	/* Fields.

	   Requested fields.
	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update dashboard layout component params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDashboardLayoutComponentParams) WithDefaults() *UpdateDashboardLayoutComponentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update dashboard layout component params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDashboardLayoutComponentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithTimeout(timeout time.Duration) *UpdateDashboardLayoutComponentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithContext(ctx context.Context) *UpdateDashboardLayoutComponentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithHTTPClient(client *http.Client) *UpdateDashboardLayoutComponentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithBody(body *models.DashboardLayoutComponent) *UpdateDashboardLayoutComponentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetBody(body *models.DashboardLayoutComponent) {
	o.Body = body
}

// WithDashboardLayoutComponentID adds the dashboardLayoutComponentID to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithDashboardLayoutComponentID(dashboardLayoutComponentID string) *UpdateDashboardLayoutComponentParams {
	o.SetDashboardLayoutComponentID(dashboardLayoutComponentID)
	return o
}

// SetDashboardLayoutComponentID adds the dashboardLayoutComponentId to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetDashboardLayoutComponentID(dashboardLayoutComponentID string) {
	o.DashboardLayoutComponentID = dashboardLayoutComponentID
}

// WithFields adds the fields to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) WithFields(fields *string) *UpdateDashboardLayoutComponentParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the update dashboard layout component params
func (o *UpdateDashboardLayoutComponentParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDashboardLayoutComponentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param dashboard_layout_component_id
	if err := r.SetPathParam("dashboard_layout_component_id", o.DashboardLayoutComponentID); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
