// Code generated by go-swagger; DO NOT EDIT.

package color_collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Foxtel-DnA/looker-go-sdk/models"
)

// NewCreateColorCollectionParams creates a new CreateColorCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateColorCollectionParams() *CreateColorCollectionParams {
	return &CreateColorCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateColorCollectionParamsWithTimeout creates a new CreateColorCollectionParams object
// with the ability to set a timeout on a request.
func NewCreateColorCollectionParamsWithTimeout(timeout time.Duration) *CreateColorCollectionParams {
	return &CreateColorCollectionParams{
		timeout: timeout,
	}
}

// NewCreateColorCollectionParamsWithContext creates a new CreateColorCollectionParams object
// with the ability to set a context for a request.
func NewCreateColorCollectionParamsWithContext(ctx context.Context) *CreateColorCollectionParams {
	return &CreateColorCollectionParams{
		Context: ctx,
	}
}

// NewCreateColorCollectionParamsWithHTTPClient creates a new CreateColorCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateColorCollectionParamsWithHTTPClient(client *http.Client) *CreateColorCollectionParams {
	return &CreateColorCollectionParams{
		HTTPClient: client,
	}
}

/* CreateColorCollectionParams contains all the parameters to send to the API endpoint
   for the create color collection operation.

   Typically these are written to a http.Request.
*/
type CreateColorCollectionParams struct {

	/* Body.

	   ColorCollection
	*/
	Body *models.ColorCollection

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create color collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateColorCollectionParams) WithDefaults() *CreateColorCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create color collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateColorCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create color collection params
func (o *CreateColorCollectionParams) WithTimeout(timeout time.Duration) *CreateColorCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create color collection params
func (o *CreateColorCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create color collection params
func (o *CreateColorCollectionParams) WithContext(ctx context.Context) *CreateColorCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create color collection params
func (o *CreateColorCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create color collection params
func (o *CreateColorCollectionParams) WithHTTPClient(client *http.Client) *CreateColorCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create color collection params
func (o *CreateColorCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create color collection params
func (o *CreateColorCollectionParams) WithBody(body *models.ColorCollection) *CreateColorCollectionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create color collection params
func (o *CreateColorCollectionParams) SetBody(body *models.ColorCollection) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateColorCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
