// Code generated by go-swagger; DO NOT EDIT.

package color_collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteColorCollectionParams creates a new DeleteColorCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteColorCollectionParams() *DeleteColorCollectionParams {
	return &DeleteColorCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteColorCollectionParamsWithTimeout creates a new DeleteColorCollectionParams object
// with the ability to set a timeout on a request.
func NewDeleteColorCollectionParamsWithTimeout(timeout time.Duration) *DeleteColorCollectionParams {
	return &DeleteColorCollectionParams{
		timeout: timeout,
	}
}

// NewDeleteColorCollectionParamsWithContext creates a new DeleteColorCollectionParams object
// with the ability to set a context for a request.
func NewDeleteColorCollectionParamsWithContext(ctx context.Context) *DeleteColorCollectionParams {
	return &DeleteColorCollectionParams{
		Context: ctx,
	}
}

// NewDeleteColorCollectionParamsWithHTTPClient creates a new DeleteColorCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteColorCollectionParamsWithHTTPClient(client *http.Client) *DeleteColorCollectionParams {
	return &DeleteColorCollectionParams{
		HTTPClient: client,
	}
}

/* DeleteColorCollectionParams contains all the parameters to send to the API endpoint
   for the delete color collection operation.

   Typically these are written to a http.Request.
*/
type DeleteColorCollectionParams struct {

	/* CollectionID.

	   Id of Color Collection
	*/
	CollectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete color collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteColorCollectionParams) WithDefaults() *DeleteColorCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete color collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteColorCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete color collection params
func (o *DeleteColorCollectionParams) WithTimeout(timeout time.Duration) *DeleteColorCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete color collection params
func (o *DeleteColorCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete color collection params
func (o *DeleteColorCollectionParams) WithContext(ctx context.Context) *DeleteColorCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete color collection params
func (o *DeleteColorCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete color collection params
func (o *DeleteColorCollectionParams) WithHTTPClient(client *http.Client) *DeleteColorCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete color collection params
func (o *DeleteColorCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the delete color collection params
func (o *DeleteColorCollectionParams) WithCollectionID(collectionID string) *DeleteColorCollectionParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the delete color collection params
func (o *DeleteColorCollectionParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteColorCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collection_id
	if err := r.SetPathParam("collection_id", o.CollectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
