// Code generated by go-swagger; DO NOT EDIT.

package api_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Foxtel-DnA/looker-go-sdk/models"
)

// LogoutReader is a Reader for the Logout structure.
type LogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewLogoutNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLogoutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLogoutNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLogoutNoContent creates a LogoutNoContent with default headers values
func NewLogoutNoContent() *LogoutNoContent {
	return &LogoutNoContent{}
}

/* LogoutNoContent describes a response with status code 204, with default header values.

Logged out successfully.
*/
type LogoutNoContent struct {
	Payload string
}

func (o *LogoutNoContent) Error() string {
	return fmt.Sprintf("[DELETE /logout][%d] logoutNoContent  %+v", 204, o.Payload)
}
func (o *LogoutNoContent) GetPayload() string {
	return o.Payload
}

func (o *LogoutNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogoutBadRequest creates a LogoutBadRequest with default headers values
func NewLogoutBadRequest() *LogoutBadRequest {
	return &LogoutBadRequest{}
}

/* LogoutBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type LogoutBadRequest struct {
	Payload *models.Error
}

func (o *LogoutBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /logout][%d] logoutBadRequest  %+v", 400, o.Payload)
}
func (o *LogoutBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *LogoutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogoutNotFound creates a LogoutNotFound with default headers values
func NewLogoutNotFound() *LogoutNotFound {
	return &LogoutNotFound{}
}

/* LogoutNotFound describes a response with status code 404, with default header values.

Not Found
*/
type LogoutNotFound struct {
	Payload *models.Error
}

func (o *LogoutNotFound) Error() string {
	return fmt.Sprintf("[DELETE /logout][%d] logoutNotFound  %+v", 404, o.Payload)
}
func (o *LogoutNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *LogoutNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
