// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteUserAttributeUserValueParams creates a new DeleteUserAttributeUserValueParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteUserAttributeUserValueParams() *DeleteUserAttributeUserValueParams {
	return &DeleteUserAttributeUserValueParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserAttributeUserValueParamsWithTimeout creates a new DeleteUserAttributeUserValueParams object
// with the ability to set a timeout on a request.
func NewDeleteUserAttributeUserValueParamsWithTimeout(timeout time.Duration) *DeleteUserAttributeUserValueParams {
	return &DeleteUserAttributeUserValueParams{
		timeout: timeout,
	}
}

// NewDeleteUserAttributeUserValueParamsWithContext creates a new DeleteUserAttributeUserValueParams object
// with the ability to set a context for a request.
func NewDeleteUserAttributeUserValueParamsWithContext(ctx context.Context) *DeleteUserAttributeUserValueParams {
	return &DeleteUserAttributeUserValueParams{
		Context: ctx,
	}
}

// NewDeleteUserAttributeUserValueParamsWithHTTPClient creates a new DeleteUserAttributeUserValueParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteUserAttributeUserValueParamsWithHTTPClient(client *http.Client) *DeleteUserAttributeUserValueParams {
	return &DeleteUserAttributeUserValueParams{
		HTTPClient: client,
	}
}

/* DeleteUserAttributeUserValueParams contains all the parameters to send to the API endpoint
   for the delete user attribute user value operation.

   Typically these are written to a http.Request.
*/
type DeleteUserAttributeUserValueParams struct {

	/* UserAttributeID.

	   Id of user attribute

	   Format: int64
	*/
	UserAttributeID int64

	/* UserID.

	   Id of user

	   Format: int64
	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete user attribute user value params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserAttributeUserValueParams) WithDefaults() *DeleteUserAttributeUserValueParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete user attribute user value params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserAttributeUserValueParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) WithTimeout(timeout time.Duration) *DeleteUserAttributeUserValueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) WithContext(ctx context.Context) *DeleteUserAttributeUserValueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) WithHTTPClient(client *http.Client) *DeleteUserAttributeUserValueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserAttributeID adds the userAttributeID to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) WithUserAttributeID(userAttributeID int64) *DeleteUserAttributeUserValueParams {
	o.SetUserAttributeID(userAttributeID)
	return o
}

// SetUserAttributeID adds the userAttributeId to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) SetUserAttributeID(userAttributeID int64) {
	o.UserAttributeID = userAttributeID
}

// WithUserID adds the userID to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) WithUserID(userID int64) *DeleteUserAttributeUserValueParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete user attribute user value params
func (o *DeleteUserAttributeUserValueParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserAttributeUserValueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_attribute_id
	if err := r.SetPathParam("user_attribute_id", swag.FormatInt64(o.UserAttributeID)); err != nil {
		return err
	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
