// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUserCredentialsOidcParams creates a new UserCredentialsOidcParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUserCredentialsOidcParams() *UserCredentialsOidcParams {
	return &UserCredentialsOidcParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUserCredentialsOidcParamsWithTimeout creates a new UserCredentialsOidcParams object
// with the ability to set a timeout on a request.
func NewUserCredentialsOidcParamsWithTimeout(timeout time.Duration) *UserCredentialsOidcParams {
	return &UserCredentialsOidcParams{
		timeout: timeout,
	}
}

// NewUserCredentialsOidcParamsWithContext creates a new UserCredentialsOidcParams object
// with the ability to set a context for a request.
func NewUserCredentialsOidcParamsWithContext(ctx context.Context) *UserCredentialsOidcParams {
	return &UserCredentialsOidcParams{
		Context: ctx,
	}
}

// NewUserCredentialsOidcParamsWithHTTPClient creates a new UserCredentialsOidcParams object
// with the ability to set a custom HTTPClient for a request.
func NewUserCredentialsOidcParamsWithHTTPClient(client *http.Client) *UserCredentialsOidcParams {
	return &UserCredentialsOidcParams{
		HTTPClient: client,
	}
}

/* UserCredentialsOidcParams contains all the parameters to send to the API endpoint
   for the user credentials oidc operation.

   Typically these are written to a http.Request.
*/
type UserCredentialsOidcParams struct {

	/* Fields.

	   Requested fields.
	*/
	Fields *string

	/* UserID.

	   id of user

	   Format: int64
	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the user credentials oidc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserCredentialsOidcParams) WithDefaults() *UserCredentialsOidcParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the user credentials oidc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UserCredentialsOidcParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the user credentials oidc params
func (o *UserCredentialsOidcParams) WithTimeout(timeout time.Duration) *UserCredentialsOidcParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user credentials oidc params
func (o *UserCredentialsOidcParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user credentials oidc params
func (o *UserCredentialsOidcParams) WithContext(ctx context.Context) *UserCredentialsOidcParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user credentials oidc params
func (o *UserCredentialsOidcParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user credentials oidc params
func (o *UserCredentialsOidcParams) WithHTTPClient(client *http.Client) *UserCredentialsOidcParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user credentials oidc params
func (o *UserCredentialsOidcParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the user credentials oidc params
func (o *UserCredentialsOidcParams) WithFields(fields *string) *UserCredentialsOidcParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the user credentials oidc params
func (o *UserCredentialsOidcParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithUserID adds the userID to the user credentials oidc params
func (o *UserCredentialsOidcParams) WithUserID(userID int64) *UserCredentialsOidcParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the user credentials oidc params
func (o *UserCredentialsOidcParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *UserCredentialsOidcParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param user_id
	if err := r.SetPathParam("user_id", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
