// Code generated by go-swagger; DO NOT EDIT.

package integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"your-damain.com/swagger/looker-api-golang/models"
)

// UpdateIntegrationHubReader is a Reader for the UpdateIntegrationHub structure.
type UpdateIntegrationHubReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateIntegrationHubReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateIntegrationHubOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateIntegrationHubBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateIntegrationHubNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateIntegrationHubUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewUpdateIntegrationHubTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateIntegrationHubOK creates a UpdateIntegrationHubOK with default headers values
func NewUpdateIntegrationHubOK() *UpdateIntegrationHubOK {
	return &UpdateIntegrationHubOK{}
}

/* UpdateIntegrationHubOK describes a response with status code 200, with default header values.

Integration Hub
*/
type UpdateIntegrationHubOK struct {
	Payload *models.IntegrationHub
}

func (o *UpdateIntegrationHubOK) Error() string {
	return fmt.Sprintf("[PATCH /integration_hubs/{integration_hub_id}][%d] updateIntegrationHubOK  %+v", 200, o.Payload)
}
func (o *UpdateIntegrationHubOK) GetPayload() *models.IntegrationHub {
	return o.Payload
}

func (o *UpdateIntegrationHubOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntegrationHub)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIntegrationHubBadRequest creates a UpdateIntegrationHubBadRequest with default headers values
func NewUpdateIntegrationHubBadRequest() *UpdateIntegrationHubBadRequest {
	return &UpdateIntegrationHubBadRequest{}
}

/* UpdateIntegrationHubBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateIntegrationHubBadRequest struct {
	Payload *models.Error
}

func (o *UpdateIntegrationHubBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /integration_hubs/{integration_hub_id}][%d] updateIntegrationHubBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateIntegrationHubBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateIntegrationHubBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIntegrationHubNotFound creates a UpdateIntegrationHubNotFound with default headers values
func NewUpdateIntegrationHubNotFound() *UpdateIntegrationHubNotFound {
	return &UpdateIntegrationHubNotFound{}
}

/* UpdateIntegrationHubNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateIntegrationHubNotFound struct {
	Payload *models.Error
}

func (o *UpdateIntegrationHubNotFound) Error() string {
	return fmt.Sprintf("[PATCH /integration_hubs/{integration_hub_id}][%d] updateIntegrationHubNotFound  %+v", 404, o.Payload)
}
func (o *UpdateIntegrationHubNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateIntegrationHubNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIntegrationHubUnprocessableEntity creates a UpdateIntegrationHubUnprocessableEntity with default headers values
func NewUpdateIntegrationHubUnprocessableEntity() *UpdateIntegrationHubUnprocessableEntity {
	return &UpdateIntegrationHubUnprocessableEntity{}
}

/* UpdateIntegrationHubUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type UpdateIntegrationHubUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *UpdateIntegrationHubUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PATCH /integration_hubs/{integration_hub_id}][%d] updateIntegrationHubUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *UpdateIntegrationHubUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateIntegrationHubUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateIntegrationHubTooManyRequests creates a UpdateIntegrationHubTooManyRequests with default headers values
func NewUpdateIntegrationHubTooManyRequests() *UpdateIntegrationHubTooManyRequests {
	return &UpdateIntegrationHubTooManyRequests{}
}

/* UpdateIntegrationHubTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type UpdateIntegrationHubTooManyRequests struct {
	Payload *models.Error
}

func (o *UpdateIntegrationHubTooManyRequests) Error() string {
	return fmt.Sprintf("[PATCH /integration_hubs/{integration_hub_id}][%d] updateIntegrationHubTooManyRequests  %+v", 429, o.Payload)
}
func (o *UpdateIntegrationHubTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateIntegrationHubTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
