// Code generated by go-swagger; DO NOT EDIT.

package integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Foxtel-DnA/looker-go-sdk/models"
)

// NewUpdateIntegrationHubParams creates a new UpdateIntegrationHubParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateIntegrationHubParams() *UpdateIntegrationHubParams {
	return &UpdateIntegrationHubParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateIntegrationHubParamsWithTimeout creates a new UpdateIntegrationHubParams object
// with the ability to set a timeout on a request.
func NewUpdateIntegrationHubParamsWithTimeout(timeout time.Duration) *UpdateIntegrationHubParams {
	return &UpdateIntegrationHubParams{
		timeout: timeout,
	}
}

// NewUpdateIntegrationHubParamsWithContext creates a new UpdateIntegrationHubParams object
// with the ability to set a context for a request.
func NewUpdateIntegrationHubParamsWithContext(ctx context.Context) *UpdateIntegrationHubParams {
	return &UpdateIntegrationHubParams{
		Context: ctx,
	}
}

// NewUpdateIntegrationHubParamsWithHTTPClient creates a new UpdateIntegrationHubParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateIntegrationHubParamsWithHTTPClient(client *http.Client) *UpdateIntegrationHubParams {
	return &UpdateIntegrationHubParams{
		HTTPClient: client,
	}
}

/* UpdateIntegrationHubParams contains all the parameters to send to the API endpoint
   for the update integration hub operation.

   Typically these are written to a http.Request.
*/
type UpdateIntegrationHubParams struct {

	/* Body.

	   Integration Hub
	*/
	Body *models.IntegrationHub

	/* Fields.

	   Requested fields.
	*/
	Fields *string

	/* IntegrationHubID.

	   Id of Integration Hub

	   Format: int64
	*/
	IntegrationHubID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update integration hub params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateIntegrationHubParams) WithDefaults() *UpdateIntegrationHubParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update integration hub params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateIntegrationHubParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update integration hub params
func (o *UpdateIntegrationHubParams) WithTimeout(timeout time.Duration) *UpdateIntegrationHubParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update integration hub params
func (o *UpdateIntegrationHubParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update integration hub params
func (o *UpdateIntegrationHubParams) WithContext(ctx context.Context) *UpdateIntegrationHubParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update integration hub params
func (o *UpdateIntegrationHubParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update integration hub params
func (o *UpdateIntegrationHubParams) WithHTTPClient(client *http.Client) *UpdateIntegrationHubParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update integration hub params
func (o *UpdateIntegrationHubParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update integration hub params
func (o *UpdateIntegrationHubParams) WithBody(body *models.IntegrationHub) *UpdateIntegrationHubParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update integration hub params
func (o *UpdateIntegrationHubParams) SetBody(body *models.IntegrationHub) {
	o.Body = body
}

// WithFields adds the fields to the update integration hub params
func (o *UpdateIntegrationHubParams) WithFields(fields *string) *UpdateIntegrationHubParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the update integration hub params
func (o *UpdateIntegrationHubParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithIntegrationHubID adds the integrationHubID to the update integration hub params
func (o *UpdateIntegrationHubParams) WithIntegrationHubID(integrationHubID int64) *UpdateIntegrationHubParams {
	o.SetIntegrationHubID(integrationHubID)
	return o
}

// SetIntegrationHubID adds the integrationHubId to the update integration hub params
func (o *UpdateIntegrationHubParams) SetIntegrationHubID(integrationHubID int64) {
	o.IntegrationHubID = integrationHubID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateIntegrationHubParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	// path param integration_hub_id
	if err := r.SetPathParam("integration_hub_id", swag.FormatInt64(o.IntegrationHubID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
