// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAllUserLoginLockoutsParams creates a new AllUserLoginLockoutsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAllUserLoginLockoutsParams() *AllUserLoginLockoutsParams {
	return &AllUserLoginLockoutsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAllUserLoginLockoutsParamsWithTimeout creates a new AllUserLoginLockoutsParams object
// with the ability to set a timeout on a request.
func NewAllUserLoginLockoutsParamsWithTimeout(timeout time.Duration) *AllUserLoginLockoutsParams {
	return &AllUserLoginLockoutsParams{
		timeout: timeout,
	}
}

// NewAllUserLoginLockoutsParamsWithContext creates a new AllUserLoginLockoutsParams object
// with the ability to set a context for a request.
func NewAllUserLoginLockoutsParamsWithContext(ctx context.Context) *AllUserLoginLockoutsParams {
	return &AllUserLoginLockoutsParams{
		Context: ctx,
	}
}

// NewAllUserLoginLockoutsParamsWithHTTPClient creates a new AllUserLoginLockoutsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAllUserLoginLockoutsParamsWithHTTPClient(client *http.Client) *AllUserLoginLockoutsParams {
	return &AllUserLoginLockoutsParams{
		HTTPClient: client,
	}
}

/* AllUserLoginLockoutsParams contains all the parameters to send to the API endpoint
   for the all user login lockouts operation.

   Typically these are written to a http.Request.
*/
type AllUserLoginLockoutsParams struct {

	/* Fields.

	   Include only these fields in the response
	*/
	Fields *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the all user login lockouts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AllUserLoginLockoutsParams) WithDefaults() *AllUserLoginLockoutsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the all user login lockouts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AllUserLoginLockoutsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) WithTimeout(timeout time.Duration) *AllUserLoginLockoutsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) WithContext(ctx context.Context) *AllUserLoginLockoutsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) WithHTTPClient(client *http.Client) *AllUserLoginLockoutsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) WithFields(fields *string) *AllUserLoginLockoutsParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the all user login lockouts params
func (o *AllUserLoginLockoutsParams) SetFields(fields *string) {
	o.Fields = fields
}

// WriteToRequest writes these params to a swagger request
func (o *AllUserLoginLockoutsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
