// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Foxtel-DnA/looker-go-sdk/models"
)

// CreateSamlTestConfigReader is a Reader for the CreateSamlTestConfig structure.
type CreateSamlTestConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSamlTestConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSamlTestConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSamlTestConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateSamlTestConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateSamlTestConfigUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateSamlTestConfigOK creates a CreateSamlTestConfigOK with default headers values
func NewCreateSamlTestConfigOK() *CreateSamlTestConfigOK {
	return &CreateSamlTestConfigOK{}
}

/* CreateSamlTestConfigOK describes a response with status code 200, with default header values.

SAML test config
*/
type CreateSamlTestConfigOK struct {
	Payload *models.SamlConfig
}

func (o *CreateSamlTestConfigOK) Error() string {
	return fmt.Sprintf("[POST /saml_test_configs][%d] createSamlTestConfigOK  %+v", 200, o.Payload)
}
func (o *CreateSamlTestConfigOK) GetPayload() *models.SamlConfig {
	return o.Payload
}

func (o *CreateSamlTestConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SamlConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSamlTestConfigBadRequest creates a CreateSamlTestConfigBadRequest with default headers values
func NewCreateSamlTestConfigBadRequest() *CreateSamlTestConfigBadRequest {
	return &CreateSamlTestConfigBadRequest{}
}

/* CreateSamlTestConfigBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateSamlTestConfigBadRequest struct {
	Payload *models.Error
}

func (o *CreateSamlTestConfigBadRequest) Error() string {
	return fmt.Sprintf("[POST /saml_test_configs][%d] createSamlTestConfigBadRequest  %+v", 400, o.Payload)
}
func (o *CreateSamlTestConfigBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSamlTestConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSamlTestConfigNotFound creates a CreateSamlTestConfigNotFound with default headers values
func NewCreateSamlTestConfigNotFound() *CreateSamlTestConfigNotFound {
	return &CreateSamlTestConfigNotFound{}
}

/* CreateSamlTestConfigNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateSamlTestConfigNotFound struct {
	Payload *models.Error
}

func (o *CreateSamlTestConfigNotFound) Error() string {
	return fmt.Sprintf("[POST /saml_test_configs][%d] createSamlTestConfigNotFound  %+v", 404, o.Payload)
}
func (o *CreateSamlTestConfigNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSamlTestConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSamlTestConfigUnprocessableEntity creates a CreateSamlTestConfigUnprocessableEntity with default headers values
func NewCreateSamlTestConfigUnprocessableEntity() *CreateSamlTestConfigUnprocessableEntity {
	return &CreateSamlTestConfigUnprocessableEntity{}
}

/* CreateSamlTestConfigUnprocessableEntity describes a response with status code 422, with default header values.

Validation Error
*/
type CreateSamlTestConfigUnprocessableEntity struct {
	Payload *models.ValidationError
}

func (o *CreateSamlTestConfigUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /saml_test_configs][%d] createSamlTestConfigUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateSamlTestConfigUnprocessableEntity) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *CreateSamlTestConfigUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
