// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Foxtel-DnA/looker-go-sdk/models"
)

// NewUpdateRepositoryCredentialParams creates a new UpdateRepositoryCredentialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRepositoryCredentialParams() *UpdateRepositoryCredentialParams {
	return &UpdateRepositoryCredentialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepositoryCredentialParamsWithTimeout creates a new UpdateRepositoryCredentialParams object
// with the ability to set a timeout on a request.
func NewUpdateRepositoryCredentialParamsWithTimeout(timeout time.Duration) *UpdateRepositoryCredentialParams {
	return &UpdateRepositoryCredentialParams{
		timeout: timeout,
	}
}

// NewUpdateRepositoryCredentialParamsWithContext creates a new UpdateRepositoryCredentialParams object
// with the ability to set a context for a request.
func NewUpdateRepositoryCredentialParamsWithContext(ctx context.Context) *UpdateRepositoryCredentialParams {
	return &UpdateRepositoryCredentialParams{
		Context: ctx,
	}
}

// NewUpdateRepositoryCredentialParamsWithHTTPClient creates a new UpdateRepositoryCredentialParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRepositoryCredentialParamsWithHTTPClient(client *http.Client) *UpdateRepositoryCredentialParams {
	return &UpdateRepositoryCredentialParams{
		HTTPClient: client,
	}
}

/* UpdateRepositoryCredentialParams contains all the parameters to send to the API endpoint
   for the update repository credential operation.

   Typically these are written to a http.Request.
*/
type UpdateRepositoryCredentialParams struct {

	/* Body.

	   Remote Project Information
	*/
	Body *models.RepositoryCredential

	/* CredentialID.

	   Credential Id
	*/
	CredentialID string

	/* RootProjectID.

	   Root Project Id
	*/
	RootProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repository credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepositoryCredentialParams) WithDefaults() *UpdateRepositoryCredentialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repository credential params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepositoryCredentialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithTimeout(timeout time.Duration) *UpdateRepositoryCredentialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithContext(ctx context.Context) *UpdateRepositoryCredentialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithHTTPClient(client *http.Client) *UpdateRepositoryCredentialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithBody(body *models.RepositoryCredential) *UpdateRepositoryCredentialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetBody(body *models.RepositoryCredential) {
	o.Body = body
}

// WithCredentialID adds the credentialID to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithCredentialID(credentialID string) *UpdateRepositoryCredentialParams {
	o.SetCredentialID(credentialID)
	return o
}

// SetCredentialID adds the credentialId to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetCredentialID(credentialID string) {
	o.CredentialID = credentialID
}

// WithRootProjectID adds the rootProjectID to the update repository credential params
func (o *UpdateRepositoryCredentialParams) WithRootProjectID(rootProjectID string) *UpdateRepositoryCredentialParams {
	o.SetRootProjectID(rootProjectID)
	return o
}

// SetRootProjectID adds the rootProjectId to the update repository credential params
func (o *UpdateRepositoryCredentialParams) SetRootProjectID(rootProjectID string) {
	o.RootProjectID = rootProjectID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepositoryCredentialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param credential_id
	if err := r.SetPathParam("credential_id", o.CredentialID); err != nil {
		return err
	}

	// path param root_project_id
	if err := r.SetPathParam("root_project_id", o.RootProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
