// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContentValidationDashboardElement content validation dashboard element
//
// swagger:model ContentValidationDashboardElement
type ContentValidationDashboardElement struct {

	// Text tile body text
	BodyText string `json:"body_text,omitempty"`

	// Id of Dashboard
	DashboardID string `json:"dashboard_id,omitempty"`

	// Unique Id
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Id Of Look
	LookID string `json:"look_id,omitempty"`

	// Note Display
	NoteDisplay string `json:"note_display,omitempty"`

	// Note State
	NoteState string `json:"note_state,omitempty"`

	// Note Text
	NoteText string `json:"note_text,omitempty"`

	// Note Text as Html
	// Read Only: true
	NoteTextAsHTML string `json:"note_text_as_html,omitempty"`

	// Id Of Query
	QueryID int64 `json:"query_id,omitempty"`

	// Text tile subtitle text
	SubtitleText string `json:"subtitle_text,omitempty"`

	// Title of dashboard element
	Title string `json:"title,omitempty"`

	// Whether title is hidden
	TitleHidden bool `json:"title_hidden,omitempty"`

	// Text tile title
	TitleText string `json:"title_text,omitempty"`

	// Type
	Type string `json:"type,omitempty"`
}

// Validate validates this content validation dashboard element
func (m *ContentValidationDashboardElement) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this content validation dashboard element based on the context it is used
func (m *ContentValidationDashboardElement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNoteTextAsHTML(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContentValidationDashboardElement) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *ContentValidationDashboardElement) contextValidateNoteTextAsHTML(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "note_text_as_html", "body", string(m.NoteTextAsHTML)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContentValidationDashboardElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentValidationDashboardElement) UnmarshalBinary(b []byte) error {
	var res ContentValidationDashboardElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
