// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContentValidationScheduledPlan content validation scheduled plan
//
// swagger:model ContentValidationScheduledPlan
type ContentValidationScheduledPlan struct {

	// Unique Id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Id of a look
	LookID int64 `json:"look_id,omitempty"`

	// Name of this scheduled plan
	Name string `json:"name,omitempty"`
}

// Validate validates this content validation scheduled plan
func (m *ContentValidationScheduledPlan) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this content validation scheduled plan based on the context it is used
func (m *ContentValidationScheduledPlan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContentValidationScheduledPlan) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContentValidationScheduledPlan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentValidationScheduledPlan) UnmarshalBinary(b []byte) error {
	var res ContentValidationScheduledPlan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
