// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CredentialsLookerOpenid credentials looker openid
//
// swagger:model CredentialsLookerOpenid
type CredentialsLookerOpenid struct {

	// Operations the current user is able to perform on this object
	// Read Only: true
	Can map[string]bool `json:"can,omitempty"`

	// Timestamp for the creation of this credential
	// Read Only: true
	CreatedAt string `json:"created_at,omitempty"`

	// EMail address used for user login
	// Read Only: true
	Email string `json:"email,omitempty"`

	// Has this credential been disabled?
	// Read Only: true
	IsDisabled *bool `json:"is_disabled,omitempty"`

	// Timestamp for most recent login using credential
	// Read Only: true
	LoggedInAt string `json:"logged_in_at,omitempty"`

	// IP address of client for most recent login using credential
	// Read Only: true
	LoggedInIP string `json:"logged_in_ip,omitempty"`

	// Short name for the type of this kind of credential
	// Read Only: true
	Type string `json:"type,omitempty"`

	// Link to get this item
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// Link to get this user
	// Read Only: true
	// Format: uri
	UserURL strfmt.URI `json:"user_url,omitempty"`
}

// Validate validates this credentials looker openid
func (m *CredentialsLookerOpenid) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialsLookerOpenid) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) validateUserURL(formats strfmt.Registry) error {
	if swag.IsZero(m.UserURL) { // not required
		return nil
	}

	if err := validate.FormatOf("user_url", "body", "uri", m.UserURL.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this credentials looker openid based on the context it is used
func (m *CredentialsLookerOpenid) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCan(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEmail(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIsDisabled(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLoggedInAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLoggedInIP(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialsLookerOpenid) contextValidateCan(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created_at", "body", string(m.CreatedAt)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateEmail(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "email", "body", string(m.Email)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateIsDisabled(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "is_disabled", "body", m.IsDisabled); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateLoggedInAt(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "logged_in_at", "body", string(m.LoggedInAt)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateLoggedInIP(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "logged_in_ip", "body", string(m.LoggedInIP)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(m.Type)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "url", "body", strfmt.URI(m.URL)); err != nil {
		return err
	}

	return nil
}

func (m *CredentialsLookerOpenid) contextValidateUserURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "user_url", "body", strfmt.URI(m.UserURL)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CredentialsLookerOpenid) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialsLookerOpenid) UnmarshalBinary(b []byte) error {
	var res CredentialsLookerOpenid
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
