// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LocalizationSettings localization settings
//
// swagger:model LocalizationSettings
type LocalizationSettings struct {

	// Operations the current user is able to perform on this object
	// Read Only: true
	Can map[string]bool `json:"can,omitempty"`

	// Default locale for localization
	// Read Only: true
	DefaultLocale string `json:"default_locale,omitempty"`

	// Localization level - strict or permissive
	// Read Only: true
	LocalizationLevel string `json:"localization_level,omitempty"`
}

// Validate validates this localization settings
func (m *LocalizationSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this localization settings based on the context it is used
func (m *LocalizationSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCan(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDefaultLocale(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLocalizationLevel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LocalizationSettings) contextValidateCan(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *LocalizationSettings) contextValidateDefaultLocale(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "default_locale", "body", string(m.DefaultLocale)); err != nil {
		return err
	}

	return nil
}

func (m *LocalizationSettings) contextValidateLocalizationLevel(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "localization_level", "body", string(m.LocalizationLevel)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LocalizationSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LocalizationSettings) UnmarshalBinary(b []byte) error {
	var res LocalizationSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
