// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LookmlModelExploreFieldMeasureFilters lookml model explore field measure filters
//
// swagger:model LookmlModelExploreFieldMeasureFilters
type LookmlModelExploreFieldMeasureFilters struct {

	// Filter condition value
	// Read Only: true
	Condition string `json:"condition,omitempty"`

	// Filter field name
	// Read Only: true
	Field string `json:"field,omitempty"`
}

// Validate validates this lookml model explore field measure filters
func (m *LookmlModelExploreFieldMeasureFilters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this lookml model explore field measure filters based on the context it is used
func (m *LookmlModelExploreFieldMeasureFilters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCondition(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateField(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LookmlModelExploreFieldMeasureFilters) contextValidateCondition(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "condition", "body", string(m.Condition)); err != nil {
		return err
	}

	return nil
}

func (m *LookmlModelExploreFieldMeasureFilters) contextValidateField(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "field", "body", string(m.Field)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LookmlModelExploreFieldMeasureFilters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LookmlModelExploreFieldMeasureFilters) UnmarshalBinary(b []byte) error {
	var res LookmlModelExploreFieldMeasureFilters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
