// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WelcomeEmailTest welcome email test
//
// swagger:model WelcomeEmailTest
type WelcomeEmailTest struct {

	// The content that would be sent in the body of a custom welcome email
	Content string `json:"content,omitempty"`

	// The header that would be sent in the body of a custom welcome email
	Header string `json:"header,omitempty"`

	// The subject that would be sent for the custom welcome email
	Subject string `json:"subject,omitempty"`
}

// Validate validates this welcome email test
func (m *WelcomeEmailTest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this welcome email test based on context it is used
func (m *WelcomeEmailTest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WelcomeEmailTest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WelcomeEmailTest) UnmarshalBinary(b []byte) error {
	var res WelcomeEmailTest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
